### ISSUE TITLE
Consider to use kotlin-argparser instead of docopt

### ISSUE THREAD

**Issue by holgerbrandl** [kscripting/kscript#141]
This would give more flexibility to evolve the CLI. See https://github.com/xenomachina/kotlin-argparser

**Comment by oshai** [comment]
sounds like a good idea!

**Comment by seanabraham** [comment]
You might want to take a look at Clikt as well: https://github.com/ajalt/clikt, https://ajalt.github.io/clikt/whyclikt.html

**Comment by hanslovsky** [comment]
I have not used kotlin-argparser but I have had good experience with [picocli](https://picocli.info/) in the JVM world.

**Comment by aartiPl** [comment]
In soon-to-be-released version 4.2, DocOpt is replaced with the Apache CLI options library. Because of that, we can close this ticket.
