### ISSUE TITLE
Publish to Maven

### ISSUE THREAD

**Issue by jayvdb** [kscripting/kscript#375]
Would it be possible to publish the jar to maven?

I would like to create a Python wrapper as mentioned on https://github.com/holgerbrandl/kscript/issues/362 , and ideally want to be able to fetch and run the latest jar using https://github.com/scijava/jgo .

I see a bunch of stuff in https://search.maven.org/search?q=g:com.github.holgerbrandl , including some kscript artifact, but they dont look like the main jar.

**Comment by holgerbrandl** [comment]
Indeed the main jar is not yet published to maven-central. 

Technically it would be easy to add this to the release process, but I think @aartiPl we should reconsider the release process with you being the actual maintainer of the repo.

**Comment by aartiPl** [comment]
Yes, I agree - we should publish jars to Maven.

Regarding the release process: maybe we can create a GitHub organization named: kotlin-scripting and transfer kscript to that organization? Then we could build a release process around a new organization (user names / passwords)?

**Comment by aartiPl** [comment]
(I have also idea for another project - kotlin wrapper around bash commands. 'kotlin-scripting' organization could be hosting place for this also)

**Comment by aartiPl** [comment]
@jayvdb - great that you want to invest your time into creating a Python wrapper - effort greatly appreciated! As you can see we are not fully ready to publish Maven jar artifacts yet. But I would say it will happen sooner or later. I hope that it won't block you from starting the implementation for now.

**Comment by aartiPl** [comment]
@holgerbrandl - I have created another ticket - https://github.com/holgerbrandl/kscript/issues/376 - for discussion around release process.

**Comment by jayvdb** [comment]
@aartiPl , as I intend to build it using https://github.com/scijava/jgo , I have a hard requirement to use Maven.  The only way to get started now would be for me to publish kscript to Maven, and delete my artifact after this project is doing their own publishing to Maven.

**Comment by aartiPl** [comment]
With the 4.2.0 release KScript Maven artifact is available:
https://central.sonatype.dev/artifact/io.github.kscripting/kscript/4.2.0

I am closing this ticket as done.
