### ISSUE TITLE
KScript release process

### ISSUE THREAD

**Issue by aartiPl** [kscripting/kscript#376]
Maybe we can create a GitHub organization named: kotlin-scripting and transfer kscript to that organization? Then we could build a release process around a new organization (user names/passwords).

I have also an idea for yet another project - Kotlin wrapper around bash commands. It will allow to finally get rid of bash from user space. At least I hope for that ;-)

'kotlin-scripting' organization could be hosting place for that project also.

Please comment with your suggestions/ideas.

**Comment by holgerbrandl** [comment]
Sure thing. Great idea, first step would be to move the repo-namespace I think. Unfortunately I don't have much time in the coming months to support this process. So maybe a hard break (with transition process) is also an option to to make sure all you hard work will reach the users.

**Comment by aartiPl** [comment]
Ok. Then I will work on migration to the new organization in the next iteration. 

In the meantime can you please review the NEWS file? I have added there all the features I would like to release in kscript 4.1. I would appreciate it if you can comment on them.

To fully support updated annotations @CompilerOptions and @KotlinOptions there is a need to update kscript-annotations repository. 

Do you think you can help with releasing a new version of kscript-annotations (should happen before the release of a new version of kscript) and then the release of a new version of kscript itself?

**Comment by aartiPl** [comment]
I now have .kts script for doing releases and most of the credentials available. The script still needs to be put in the kscript repository as it depends on the not yet published library.

The changes include:
* new docker hub repository: https://hub.docker.com/r/kscripting/kscript/tags
* new homebrew repository: https://github.com/kscripting/homebrew-tap

The last part that needs to be added is the releases to ArchLinux repository. I have created my ArchLinux user (aartiPl), but now I need to become co-maintainer of the kscript repository:

https://aur.archlinux.org/packages/kscript

@holgerbrandl, @others - do you know how to become co-maintainer of kscript? Any hints how to do that correctly/quickly?

**Comment by aartiPl** [comment]
I have access to all release channels. I am closing this ticket as done.
