### ISSUE TITLE
Suppressing deprecation warnings

### ISSUE THREAD

**Issue by MagnusMG** [kscripting/kscript#384]
I use comment directives instead of annotations -- //DEPS instead of @file:DependsOn -- in order to make kscript work better in VSCode. And now I get warning from kscript every time I run my scripts:

`````
[kscript] [WARN] There are deprecated features in scripts. Use --report option to print full report.
`````
Any way of suppressing that?

**Comment by aartiPl** [comment]
Well, the plan is to remove comment-based annotations in the future. This is because it's not the best software engineering solution, and additionally, in the end, I want to use in kscript engine, which won't support such annotations anyway.

**Comment by aartiPl** [comment]
This type of annotation, which is used in kscript, is just normal Kotlin:
https://kotlinlang.org/docs/annotations.html#annotation-use-site-targets
So, please note that it is nothing new or special just for kscript.

**Comment by MagnusMG** [comment]
I seem to have found a way of making the annotation style directives work in VSCode. It is [here](https://magnusgunnarsson.se/offentlig/kscript-in-visual-studio-code-vsc/), if anybody finds this thread and wants to know.

Thanks for not giving in, aartiPI. :-)
