### ISSUE TITLE
IDEA bootstrap requires gradle or KSCRIPT_COMMAND_GRADLE set but documentation does not reflect this

### ISSUE THREAD

**Issue by dazraf** [kscripting/kscript#385]
The documentation should reflect that `gradle` is required on the path; or `KSCRIPT_COMMAND_GRADLE` needs to be set. 
Alternatively, automatically download gradle and store in somewhere reasonably local (e.g. `~/.kscript`) if not available on the path.  
Thank you.

**Comment by aartiPl** [comment]
I will relax the requirement for having Gradle and Idea in the path for the generation of the Idea projects in the next version. They will be optional. Anyway, all the PRs for improvements in the docs are warmly welcome.

**Comment by aartiPl** [comment]
The changes and documentation updates will be part of the 4.2 release.
