### ISSUE TITLE
Create kscript package for scoop

### ISSUE THREAD

**Issue by aartiPl** [kscripting/kscript#391]
There is a need for the kscript package for scoop and choco. For the starter, we need to investigate how to onboard in them quickly. Then we will need a simple release process so that I can create proper scripts.

**Comment by aartiPl** [comment]
Thanks, @goto1134, for the link to the scoop page:
https://scoop-docs.vercel.app/docs/concepts/Creating-an-app-manifest.html

**Comment by goto1134** [comment]
kscript was published to scoop by https://github.com/ScoopInstaller/Extras/pull/9353. Here is the manifest: https://github.com/ScoopInstaller/Extras/blob/master/bucket/kscript.json

1. It has the latest version already published.
2. It automatically checks for any releases in the kscript repo and updates the manifest. (see `checkver` and `autoupdate`).
3. Scoop has a special `shims` directory with symlinks to executables. For kscript, this executable is `bin\\kscript.bat`. This `shims` directory allows scoop not to modify the `PATH` after each package installation. But the current version of kscript has a bug described in https://github.com/kscripting/kscript/pull/390. Therefore https://github.com/kscripting/kscript/pull/390 should be released for kscript to work correctly with scoop.

You can install kscript on windows using the following commands:
```
scoop bucket add extras
scoop install kscript
```

**Comment by aartiPl** [comment]
@goto1134 - I have just released kscript 4.2.1 with the bug fix in kscript.bat.
As I understand, we should just wait for some automated process that will update kscript.json.

**Comment by goto1134** [comment]
Yeah, just wait for the script ☺️

**Comment by goto1134** [comment]
Finally, it was updated
https://github.com/ScoopInstaller/Extras/commit/69784ae2aad8e89f2a8b8612353717113d433a5f

😎

**Comment by goto1134** [comment]
@aartiPl , could you, please, mention [Dany-coder778](https://github.com/Dany-coder778) in the latest https://github.com/kscripting/kscript/blob/master/NEWS.adoc as the author of the scoop installer? He provided the pull request to Scoop https://github.com/ScoopInstaller/Extras/pull/9353

**Comment by aartiPl** [comment]
Sure, happy to do that. 
Thanks again for your contribution [@Dany-co!](https://github.com/Dany-coder778) and @goto1134 !
